version: "3"

services:
  redis:
    build:
      context: ./redis/master
      dockerfile: Dockerfile
    ports:
      - "6379:6379"

  redis-slave-1:
    build:
      context: ./redis/slave
      dockerfile: Dockerfile-slave1
    depends_on:
      - redis
    ports:
      - "6380:6380"

  redis-slave-2:
    build:
      context: ./redis/slave
      dockerfile: Dockerfile-slave2
    depends_on:
      - redis
      - redis-slave-1
    ports:
      - "6381:6381"

  sentinel-1:
    build:
      context: ./redis/sentinel
      dockerfile: Dockerfile-sentinel1
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - "26379:26379"

  sentinel-2:
    build:
      context: ./redis/sentinel
      dockerfile: Dockerfile-sentinel2
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - "26380:26380"

  sentinel-3:
    build:
      context: ./redis/sentinel
      dockerfile: Dockerfile-sentinel3
    depends_on:
      - redis
      - redis-slave-1
      - redis-slave-2
    ports:
      - "26381:26381"

  backend-prod:
    image: squirmm/teampple-server-prod:main
    container_name: backend-prod
    hostname: backend-prod
    expose:
      - "8080"

  client-prod:
    image: squirmm/teampple-client:main
    container_name: client-prod
    hostname: client-prod
    ports:
      - "3000:3000"

  nginx:
    depends_on:
      - backend-prod
      - client-prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
