version: "3"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  backend-prod:
    image: squirmm/teampple-server-prod:main
    container_name: backend-prod
    hostname: backend-prod
    expose:
      - "8080"

  client-prod:
    image: squirmm/teampple-client:main
    container_name: client-prod
    hostname: client-prod
    ports:
      - "3000"

  nginx:
    depends_on:
      - backend-prod
      - client-prod
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
